
import os

def build(bld):
    bld(
        features='cxx cxxprogram',
        uselib=['OPENCV', 'CUDA', 'CUDART'],
        source=bld.path.ant_glob('*.cpp') + bld.path.ant_glob('*.cu'),
        includes=['.'],
        target='PS3',
        install_path=os.path.join(bld.out_dir, 'bin'),
    )
